### ISSUE TITLE
var.admin_username and var.admin_password variables validations or preconditions

### ISSUE THREAD

**Issue by juanjojulian** [Azure/terraform-azurerm-virtual-machine#12]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

In Azure API there are a number of restrictions related to Virtual Machine 'adminUsername' and 'adminPassword':

https://learn.microsoft.com/en-us/rest/api/compute/virtual-machines/create-or-update?tabs=HTTP#osprofile

![CleanShot 2023-02-09 at 09 58 42](https://user-images.githubusercontent.com/43988825/217765567-584b8efc-b85c-4194-8d29-68db296b6da2.png)
![CleanShot 2023-02-09 at 10 04 25](https://user-images.githubusercontent.com/43988825/217766166-d5a6e51d-cfcb-444b-b1f3-d25de46ec9f5.png)

It would be nice to include a variable validation or a lifecycle precondition to verify that this restrictions are met and make the user fail fast instead of waiting for an API error. Depending if we want to apply same restrictions to Windows and Linux 'adminUsername' and 'adminPassword' or different restrictions (as in the API) we will need to follow the variable condition approach or the precondition approach. 

What do you think? 

### New or Affected Resource(s)/Data Source(s)

azurerm_linux_virtual_machine, azurerm_windows_virtual_machine

### Potential Terraform Configuration

```hcl
validation {
    condition     = !contains(["administrator", "admin", "user", "user1", "test", "user2", "test1", "user3", "admin1", "1", "123", "a", "actuser", "adm", "admin2", "aspnet", "backup", "console", "david", "guest", "john", "owner", "root", "server", "sql", "support", "support_388945a0", "sys", "test2", "test3", "user4", "user5"], var.admin_username)
    error_message = "Invalid `admin_username`."
}
```

**Comment by lonegunmanb** [comment]
Thanks @juanjojulian for opening this issue, I think we'd better to open a pr to AzrueRM Provider's repo since this should be a provider side's restriction. I can do that, but due to the limited bandwidth it might takes time. I'd like to keep this issue open until we have improved it at provider's side.

**Comment by juanjojulian** [comment]
[Issue opened in AzureRM provider](https://github.com/hashicorp/terraform-provider-azurerm/issues/20400), I will have a look to the provider code in case I can submit the PR myself, not an expert in Go.

**Comment by juanjojulian** [comment]
All validations added to the Azurerm Terraform Provider, we can close this issue now.
