### ISSUE TITLE
module versions are not updated

### ISSUE THREAD

**Issue by ozbillwang** [Azure/terraform-azurerm-virtual-machine#59]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

With Terraform registry, we are easily reference this module 

https://registry.terraform.io/modules/Azure/virtual-machine/azurerm/latest

```
module "virtual-machine" {
  source  = "Azure/virtual-machine/azurerm"
  version = "1.0.0"
  # insert the 7 required variables here
}
```
![image](https://github.com/Azure/terraform-azurerm-virtual-machine/assets/8954908/2b0f8777-fcdb-4ab6-aa1e-62001da62e55)

But currently we got new commits, but no new releases generated, still stay on the old codes based on Jun 2

![image](https://github.com/Azure/terraform-azurerm-virtual-machine/assets/8954908/fe12706f-6807-47c1-9f7b-f56c3186fce3)

### New or Affected Resource(s)/Data Source(s)

all

### Potential Terraform Configuration

```hcl
module "virtual-machine" {
  source  = "Azure/virtual-machine/azurerm"
  version = "1.0.xxx"
  # insert the 7 required variables here
}
```

### References

https://developer.hashicorp.com/terraform/language/modules/syntax

**Comment by davidkarlsen** [comment]
@ozbillwang Versions will appear after creating new tags.
