### ISSUE TITLE
Support for terraform registry

### ISSUE THREAD

**Issue by davidkarlsen** [Azure/terraform-azurerm-virtual-machine#61]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

It would be nice if this module is available through the terraform registry as well.

### New or Affected Resource(s)/Data Source(s)

N/A

### References

https://registry.terraform.io/

**Comment by lonegunmanb** [comment]
Hi @davidkarlsen thanks for opening this issue, this module is available at [registry](https://registry.terraform.io/modules/Azure/virtual-machine/azurerm/latest), is that your question?

**Comment by davidkarlsen** [comment]
doh - I must have done a bad search - sorry for the confusion.
