### ISSUE TITLE
Support for new_availability_set

### ISSUE THREAD

**Issue by anil1890** [Azure/terraform-azurerm-virtual-machine#74]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

a new Availability_set should be created when we supply new_availability_set field 

### New or Affected Resource(s)/Data Source(s)

azurerm

### Potential Terraform Configuration

```hcl
na
```

### References

na

**Comment by lonegunmanb** [comment]
Sorry for this late response @anil1890 and thanks for opening this issue to us. After reviewing this request, I decide to close this issue without any pr, since availability group is used by many other resources. We'd better to create a separated module for this resource, not in this module.
